// #####################################################################################################
// ###    This file is generated by Build and Continuous Integration scripts Github Action Runner    ###
// ###                         .github/workflows/build.yml for CI environment                        ###
// ###                    Changes will be overwritten on the next build                              ###
// #####################################################################################################
#ifndef VERSION_INFO_H
#define VERSION_INFO_H

#define CURRENT_FIRMWARE_VERSION GIT_REV
#define LAST_BUILD_FIRMWARE_VERSION "\"0.1.3\""
#define LAST_FIRMWARE_VERSION_FILENAME "\"0_1_3\""
#define LAST_COMMIT_HASH "\"e110baa\""
#define LAST_BUILD_TIMESTAMP "\"2025-Mar-24-16:23:53\""

#endif