// ##########################################################################
// ### This file is generated by Build and Continuous Integration scripts ###
// ###            .github/workflows/build.yml for CI environment          ###
// ### Changes will be overwritten on the next build                      ###
// ##########################################################################
#ifndef VERSION_INFO_H
#define VERSION_INFO_H

#define CURRENT_FIRMWARE_VERSION GIT_REV
#define LAST_BUILD_FIRMWARE_VERSION 0.0.6;
#define LAST_FIRMWARE_VERSION_FILENAME 0_0_6;
#define LAST_COMMIT_HASH 7fb9420;
#define LAST_BUILD_TIMESTAMP 2025-Mar-21-20:44:23;

#endif